# Generated by Django 3.2.9 on 2021-11-16 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0002_auto_20211114_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreManager_Surname', models.CharField(max_length=25)),
                ('StoreManager_Name', models.CharField(max_length=25)),
                ('StoreManager_MiddleName', models.CharField(max_length=25)),
                ('StoreManager_Number', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_Patronymic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_Surname',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='Provide_Address',
        ),
        migrations.RemoveField(
            model_name='receiptinvoice',
            name='Receipt_Id_Provider',
        ),
        migrations.RemoveField(
            model_name='warehouseworker',
            name='Worker_Position',
        ),
        migrations.AlterField(
            model_name='expenditureinvoice',
            name='Expend_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 7, 7, 16, 490322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Expiration_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 7, 7, 16, 487330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Production_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 7, 7, 16, 487330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='receiptinvoice',
            name='Receipt_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 7, 7, 16, 486332, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Anons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anons_NameProducts', models.CharField(blank=True, max_length=25, null=True)),
                ('Anons_SumProduct', models.IntegerField(default=0)),
                ('Anons_DateManaProducts', models.DateField(default=datetime.datetime(2021, 11, 16, 7, 7, 16, 486332, tzinfo=utc))),
                ('Anons_PriceProduct', models.IntegerField(default=0)),
                ('Anons_Id_Provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDjango.provider')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Order_StoreManager_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appDjango.storemanager'),
        ),
        migrations.AddField(
            model_name='receiptinvoice',
            name='Receipt_Id_Anons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appDjango.anons'),
        ),
    ]
