# Generated by Django 3.2.9 on 2021-11-16 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0003_auto_20211116_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anons',
            name='Anons_DateManaProducts',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 7, 52, 48, 148789, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditureinvoice',
            name='Expend_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 7, 52, 48, 153669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Expiration_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 7, 52, 48, 150741, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Production_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 7, 52, 48, 150741, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='receiptinvoice',
            name='Receipt_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 7, 52, 48, 149765, tzinfo=utc)),
        ),
    ]
