# Generated by Django 3.2.9 on 2021-11-19 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0005_auto_20211116_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_Surname', models.CharField(max_length=50)),
                ('Worker_Name', models.CharField(max_length=50)),
                ('Worker_Patronymic', models.CharField(max_length=50)),
                ('Worker_Number', models.CharField(max_length=11)),
                ('Worker_Position', models.CharField(default='some string', max_length=20)),
                ('Worker_Login', models.CharField(default='some string', max_length=25)),
                ('Worker_Password', models.CharField(default='some string', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='anons',
            name='Anons_Id_Provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_StoreManager_ID',
        ),
        migrations.AlterField(
            model_name='anons',
            name='Anons_DateManaProducts',
            field=models.DateField(default=datetime.datetime(2021, 11, 19, 10, 58, 27, 612730, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditureinvoice',
            name='Expend_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 19, 10, 58, 27, 615722, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Expiration_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 19, 10, 58, 27, 613727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Production_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 19, 10, 58, 27, 613727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='receiptinvoice',
            name='Receipt_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 19, 10, 58, 27, 612730, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='StoreManager',
        ),
        migrations.AlterField(
            model_name='arrival',
            name='ID_Worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDjango.user'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='Consumption_Id_Worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDjango.user'),
        ),
        migrations.DeleteModel(
            name='WarehouseWorker',
        ),
    ]
