# Generated by Django 3.2.9 on 2021-11-24 15:40

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0006_auto_20211119_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='anons',
            name='Anons_ID_User',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Id_User',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anons',
            name='Anons_DateManaProducts',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expenditureinvoice',
            name='Expend_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Expiration_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Production_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receiptinvoice',
            name='Receipt_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 24, 15, 40, 17, 707668, tzinfo=utc)),
        ),
    ]
