# Generated by Django 3.2.9 on 2021-12-20 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0009_auto_20211219_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_Id_Product',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='receiptinvoice',
            name='Receipt_Date',
            field=models.DateField(default=datetime.datetime(2021, 12, 20, 9, 25, 32, 83021, tzinfo=utc)),
        ),
    ]
