# Generated by Django 3.2.9 on 2021-12-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0010_auto_20211220_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptinvoice',
            name='Receipt_Id_Anons',
        ),
        migrations.AlterField(
            model_name='arrival',
            name='ID_Receipt_Invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDjango.anons'),
        ),
        migrations.DeleteModel(
            name='ExpenditureInvoice',
        ),
        migrations.DeleteModel(
            name='ReceiptInvoice',
        ),
    ]
